SELECT * FROM STUDYGROUP;

CREATE SEQUENCE SG_NO_SQ;

--스터디그룹 개설
INSERT INTO STUDYGROUP(SG_NO, SG_NAME, U_ID, SG_PERSON, SG_EXPLAIN, ST_NO)
            VALUES(SG_NO_SQ.NEXTVAL, '영어회화스터디', 'aaa', 1, '영어회화스터디 톡입니다.', 1);

SELECT * FROM STUDYMEMBER;
--타입
INSERT INTO STUDYTYPE(ST_NO, ST_NAME) VALUES(2, '컴퓨터');
--회원추가
INSERT INTO STUDYMEMBER VALUES(2, 'aaa', '2');

SELECT * FROM STUDYGROUP SG, STUDYMEMBER SM WHERE SG.SG_NO = SM.SG_NO ;
-- 회원의 스터디그룹 출력
SELECT SG_NO, SG_NAME FROM STUDYGROUP SG, USERS U WHERE U.U_ID = 'sedongdong';
--회원 탈퇴
DELETE FROM STUDYMEMBER WHERE U_ID = 'aaa';
COMMIT;
INSERT INTO STUDYGROUP(SG_NO, SG_NAME, U_ID, SG_PERSON, SG_EXPLAIN, ST_NO)
            VALUES(SG_NO_SQ.NEXTVAL, '#{sg_name}', 'sedongdong', 1, '${sg_explain}', 2);
            rollback;
-- 스터디그룹의 회원목록 출력
SELECT * FROM USERS U, STUDYMEMBER SM, STUDYGROUP SG WHERE SG.SG_NO = SM.SG_NO AND U.U_ID = SG.U_ID AND SG.SG_NAME = '영어회화스터디';