SELECT * FROM RECRUITBOARD;
SELECT * FROM RECRUITCOMMENTS;
CREATE SEQUENCE RB_SQ;
CREATE SEQUENCE RB_COM_SQ;
ALTER TABLE RECRUITBOARD
    RENAME COLUMN C_RDATE TO RB_RDATE;
ALTER TABLE RECRUITCOMMENTS
    ADD (C_RDATE TIMESTAMP DEFAULT SYSTIMESTAMP);
--LIST
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM RECRUITBOARD WHERE RB_STATUS > 0 ORDER BY RB_NO DESC) A) WHERE RN BETWEEN 1 AND 10;

--WRITING
INSERT INTO RECRUITBOARD (RB_NO, RB_NAME, RB_CONTENT, RB_STATUS, RB_HIT, U_ID)
        VALUES(RB_SQ.NEXTVAL, 'TITLE', 'CONTENT', 1, 0, 'aaa');
--COMMENT-WRITING
INSERT INTO RECRUITCOMMENTS(C_NO, U_ID, C_CONTENT, C_STATUS, RB_NO)
                        VALUES(RB_COM_SQ.NEXTVAL, 'sedongdong', 'COMMENT', 1, 2);
select count(*) from recruitcomments where rb_no = 1;                        
--DETAIL
SELECT * FROM RECRUITBOARD WHERE RB_NO = 1;
--COMMENT-DETAIL
SELECT U_ID, C_CONTENT, TO_CHAR(C_RDATE, 'YY-MM-DD HH:MI:SS') c_rdate FROM RECRUITCOMMENTS WHERE RB_NO = 1 AND C_STATUS > 0;
--UPDATE
UPDATE RECRUITBOARD SET RB_NAME = 'MODIFIED', RB_CONTENT = 'MODIFIED', RB_RDATE = SYSTIMESTAMP - INTERVAL '1' minute WHERE RB_NO = 1;
--COMMENT-UPDATE
UPDATE RECRUITCOMMENTS SET C_CONTENT = 'MODIFIED', C_RDATE = SYSTIMESTAMP - INTERVAL '1' minute WHERE C_NO = 1;
--DELETE
UPDATE RECRUITBOARD SET RB_STATUS = 0 WHERE RB_NO = 1;
--COMMENT-DELETE
UPDATE RECRUITCOMMENTS SET C_STATUS = 0 WHERE C_NO = 2;
DESC recruitboard;
desc recruitcomments;
COMMIT;

SELECT * 
			FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM RECRUITBOARD WHERE RB_STATUS > 0 ORDER BY RB_NO DESC) A) 
			WHERE RN BETWEEN 1 AND 10 AND RB_CONTENT LIKE '%'|#{schWord||'%' OR RB_NAME LIKE '%'||#{schWord}||'%'